name: qr_scanner_app
description: Offline-first QR attendance & resource collection scanner
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Local database (offline storage)
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

  # QR scanning
  mobile_scanner: ^5.1.1

  # Networking + connectivity
  http: ^1.1.0
  connectivity_plus: ^5.0.2

  # Device id + prefs
  shared_preferences: ^2.2.2
  uuid: ^4.2.1

  # Date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/members.json
    - assets/admins.json
    - assets/photos/
